/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/anime_class_room.glb -t -o app/components/models/AnimeClassRoom.tsx 
Author: AnixMoonLight (https://sketchfab.com/ani111)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anime-class-room-4faa1d57304d446995bc3a01af763239
Title: Anime Class Room
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshBasicMaterial
    ['Material.004']: THREE.MeshBasicMaterial
    ['Material.007']: THREE.MeshBasicMaterial
    ['Material.008']: THREE.MeshBasicMaterial
    ['Material.013']: THREE.MeshBasicMaterial
    ['Material.012']: THREE.MeshBasicMaterial
    ['Material.033']: THREE.MeshBasicMaterial
    ['Material.015']: THREE.MeshBasicMaterial
    ['Material.037']: THREE.MeshBasicMaterial
    ['Material.059']: THREE.MeshBasicMaterial
    ['Material.062']: THREE.MeshBasicMaterial
    None: THREE.MeshBasicMaterial
    ['Material.003']: THREE.MeshBasicMaterial
    ['Material.009']: THREE.MeshBasicMaterial
    ['Material.055']: THREE.MeshBasicMaterial
    ['Material.056']: THREE.MeshBasicMaterial
    ['Material.028']: THREE.MeshBasicMaterial
    ['Material.054']: THREE.MeshBasicMaterial
    ['.003']: THREE.MeshBasicMaterial
  }
}

export function AnimeClassRoom(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/anime_class_room.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.059']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.062']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.055']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.055']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['.003']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/anime_class_room.glb')
