/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/need_some_space.glb --types --transform 
Files: public/models/need_some_space.glb [1.4MB] > /Users/gikri/Documents/main_folder/my-website/need_some_space-transformed.glb [1.4MB] (0%)
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

'use client';

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Points
  }
  materials: {
    ['Scene_-_Root']: THREE.PointsMaterial
  }
}

export function NeedSomeSpace(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/need_some_space-transformed.glb', true) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <points geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={0.013} />
    </group>
  )
}

useGLTF.preload('models/need_some_space-transformed.glb')
