/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/space_boi.glb --types --transform --shadows 
Author: silvercrow101 (https://sketchfab.com/silvercrow101)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/space-boi-f6a8c6a6727b4f2cb020c8b50bb2ee60
Title: space boi
*/

'use client';

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    body_Material001_0: THREE.Mesh
    body_Material002_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshBasicMaterial
    ['Material.002']: THREE.MeshBasicMaterial
  }
}

export function SpaceBoi(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/space_boi-transformed.glb', true) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.body_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.body_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/space_boi-transformed.glb')
